# Air 配置文件

[build]
  # 监听以下文件扩展名的文件
  include_ext = ["go", "tpl", "tmpl", "html", "gohtml", "env"]
  # 忽略监听的目录或文件
  exclude_dir = ["vendor", "node_modules", "tmp"]
  # kill 命令延迟
  kill_delay = "0s"
  # air 的日志文件名，该日志文件放置在你的 `tmp_dir` 中
  log = "air.log"
  # 在 kill 之前发送系统中断信号，Windows 不支持此功能
  send_interrupt = false
  # error 发生时结束运行
  stop_on_error = true

[build.after]
  # 在构建之后执行的命令
  cmds = []

[log]
  # 日志级别: debug, info, warn, error, fatal, panic
  level = "info"
  # 是否启用彩色日志
  color = true
  # 是否启用时间戳
  timestamp = true

[runner]
  # 运行的命令
  cmd = "go run ."
  # 运行时的环境变量
  env = ["AIR_ENV=dev"]
  # 运行时的工作目录
  dir = "."
  # 是否启用 shell 模式
  shell = false

[watch]
  # 是否递归监听目录
  recursive = true
  # 是否忽略文件名大小写
  ignore_case = false
  # 是否监听符号链接
  follow_symlink = false