// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: domain/domain.proto

package domainPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainsRequest) Reset() {
	*x = GetDomainsRequest{}
	mi := &file_domain_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainsRequest) ProtoMessage() {}

func (x *GetDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainsRequest.ProtoReflect.Descriptor instead.
func (*GetDomainsRequest) Descriptor() ([]byte, []int) {
	return file_domain_domain_proto_rawDescGZIP(), []int{0}
}

type GetDomainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainsResponse) Reset() {
	*x = GetDomainsResponse{}
	mi := &file_domain_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainsResponse) ProtoMessage() {}

func (x *GetDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainsResponse.ProtoReflect.Descriptor instead.
func (*GetDomainsResponse) Descriptor() ([]byte, []int) {
	return file_domain_domain_proto_rawDescGZIP(), []int{1}
}

func (x *GetDomainsResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetDomainInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainInfoRequest) Reset() {
	*x = GetDomainInfoRequest{}
	mi := &file_domain_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainInfoRequest) ProtoMessage() {}

func (x *GetDomainInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDomainInfoRequest) Descriptor() ([]byte, []int) {
	return file_domain_domain_proto_rawDescGZIP(), []int{2}
}

func (x *GetDomainInfoRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetDomainInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainInfoResponse) Reset() {
	*x = GetDomainInfoResponse{}
	mi := &file_domain_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainInfoResponse) ProtoMessage() {}

func (x *GetDomainInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDomainInfoResponse) Descriptor() ([]byte, []int) {
	return file_domain_domain_proto_rawDescGZIP(), []int{3}
}

func (x *GetDomainInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDomainInfoResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetDomainInfoResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type SetDomainStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "running" or "stopped"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDomainStateRequest) Reset() {
	*x = SetDomainStateRequest{}
	mi := &file_domain_domain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDomainStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDomainStateRequest) ProtoMessage() {}

func (x *SetDomainStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_domain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDomainStateRequest.ProtoReflect.Descriptor instead.
func (*SetDomainStateRequest) Descriptor() ([]byte, []int) {
	return file_domain_domain_proto_rawDescGZIP(), []int{4}
}

func (x *SetDomainStateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SetDomainStateRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type SetDomainStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "running" or "stopped"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDomainStateResponse) Reset() {
	*x = SetDomainStateResponse{}
	mi := &file_domain_domain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDomainStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDomainStateResponse) ProtoMessage() {}

func (x *SetDomainStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_domain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDomainStateResponse.ProtoReflect.Descriptor instead.
func (*SetDomainStateResponse) Descriptor() ([]byte, []int) {
	return file_domain_domain_proto_rawDescGZIP(), []int{5}
}

func (x *SetDomainStateResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SetDomainStateResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_domain_domain_proto protoreflect.FileDescriptor

const file_domain_domain_proto_rawDesc = "" +
	"\n" +
	"\x13domain/domain.proto\x12\x06domain\"\x13\n" +
	"\x11GetDomainsRequest\".\n" +
	"\x12GetDomainsResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"*\n" +
	"\x14GetDomainInfoRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"U\n" +
	"\x15GetDomainInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"A\n" +
	"\x15SetDomainStateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"B\n" +
	"\x16SetDomainStateResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state2\xf3\x01\n" +
	"\rDomainService\x12C\n" +
	"\n" +
	"GetDomains\x12\x19.domain.GetDomainsRequest\x1a\x1a.domain.GetDomainsResponse\x12L\n" +
	"\rGetDomainInfo\x12\x1c.domain.GetDomainInfoRequest\x1a\x1d.domain.GetDomainInfoResponse\x12O\n" +
	"\x0eSetDomainState\x12\x1d.domain.SetDomainStateRequest\x1a\x1e.domain.SetDomainStateResponseB\x1bZ\x19govirt/app/proto/domainPbb\x06proto3"

var (
	file_domain_domain_proto_rawDescOnce sync.Once
	file_domain_domain_proto_rawDescData []byte
)

func file_domain_domain_proto_rawDescGZIP() []byte {
	file_domain_domain_proto_rawDescOnce.Do(func() {
		file_domain_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_domain_proto_rawDesc), len(file_domain_domain_proto_rawDesc)))
	})
	return file_domain_domain_proto_rawDescData
}

var file_domain_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_domain_domain_proto_goTypes = []any{
	(*GetDomainsRequest)(nil),      // 0: domain.GetDomainsRequest
	(*GetDomainsResponse)(nil),     // 1: domain.GetDomainsResponse
	(*GetDomainInfoRequest)(nil),   // 2: domain.GetDomainInfoRequest
	(*GetDomainInfoResponse)(nil),  // 3: domain.GetDomainInfoResponse
	(*SetDomainStateRequest)(nil),  // 4: domain.SetDomainStateRequest
	(*SetDomainStateResponse)(nil), // 5: domain.SetDomainStateResponse
}
var file_domain_domain_proto_depIdxs = []int32{
	0, // 0: domain.DomainService.GetDomains:input_type -> domain.GetDomainsRequest
	2, // 1: domain.DomainService.GetDomainInfo:input_type -> domain.GetDomainInfoRequest
	4, // 2: domain.DomainService.SetDomainState:input_type -> domain.SetDomainStateRequest
	1, // 3: domain.DomainService.GetDomains:output_type -> domain.GetDomainsResponse
	3, // 4: domain.DomainService.GetDomainInfo:output_type -> domain.GetDomainInfoResponse
	5, // 5: domain.DomainService.SetDomainState:output_type -> domain.SetDomainStateResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_domain_proto_init() }
func file_domain_domain_proto_init() {
	if File_domain_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_domain_proto_rawDesc), len(file_domain_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domain_domain_proto_goTypes,
		DependencyIndexes: file_domain_domain_proto_depIdxs,
		MessageInfos:      file_domain_domain_proto_msgTypes,
	}.Build()
	File_domain_domain_proto = out.File
	file_domain_domain_proto_goTypes = nil
	file_domain_domain_proto_depIdxs = nil
}
