// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: domain/domain.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Domain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`   // The name of the domain
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`   // The UUID of the domain
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // The state of the domain (e.g., running, shut off)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_domain_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_domain_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_domain_domain_proto_rawDescGZIP(), []int{0}
}

func (x *Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Domain) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Domain) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_domain_domain_proto protoreflect.FileDescriptor

const file_domain_domain_proto_rawDesc = "" +
	"\n" +
	"\x13domain/domain.proto\x12\x06domain\"F\n" +
	"\x06Domain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05stateB\x19Z\x17govirt/app/proto/domainb\x06proto3"

var (
	file_domain_domain_proto_rawDescOnce sync.Once
	file_domain_domain_proto_rawDescData []byte
)

func file_domain_domain_proto_rawDescGZIP() []byte {
	file_domain_domain_proto_rawDescOnce.Do(func() {
		file_domain_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_domain_proto_rawDesc), len(file_domain_domain_proto_rawDesc)))
	})
	return file_domain_domain_proto_rawDescData
}

var file_domain_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_domain_domain_proto_goTypes = []any{
	(*Domain)(nil), // 0: domain.Domain
}
var file_domain_domain_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_domain_proto_init() }
func file_domain_domain_proto_init() {
	if File_domain_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_domain_proto_rawDesc), len(file_domain_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_domain_proto_goTypes,
		DependencyIndexes: file_domain_domain_proto_depIdxs,
		MessageInfos:      file_domain_domain_proto_msgTypes,
	}.Build()
	File_domain_domain_proto = out.File
	file_domain_domain_proto_goTypes = nil
	file_domain_domain_proto_depIdxs = nil
}
