// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: libvirt/libvirt.proto

package libvirt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLibVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLibVersionRequest) Reset() {
	*x = GetLibVersionRequest{}
	mi := &file_libvirt_libvirt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLibVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibVersionRequest) ProtoMessage() {}

func (x *GetLibVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libvirt_libvirt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibVersionRequest.ProtoReflect.Descriptor instead.
func (*GetLibVersionRequest) Descriptor() ([]byte, []int) {
	return file_libvirt_libvirt_proto_rawDescGZIP(), []int{0}
}

type GetLibVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLibVersionResponse) Reset() {
	*x = GetLibVersionResponse{}
	mi := &file_libvirt_libvirt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLibVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibVersionResponse) ProtoMessage() {}

func (x *GetLibVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libvirt_libvirt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibVersionResponse.ProtoReflect.Descriptor instead.
func (*GetLibVersionResponse) Descriptor() ([]byte, []int) {
	return file_libvirt_libvirt_proto_rawDescGZIP(), []int{1}
}

func (x *GetLibVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_libvirt_libvirt_proto protoreflect.FileDescriptor

const file_libvirt_libvirt_proto_rawDesc = "" +
	"\n" +
	"\x15libvirt/libvirt.proto\x12\alibvirt\"\x16\n" +
	"\x14GetLibVersionRequest\"1\n" +
	"\x15GetLibVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion2`\n" +
	"\x0eLibvirtService\x12N\n" +
	"\rGetLibVersion\x12\x1d.libvirt.GetLibVersionRequest\x1a\x1e.libvirt.GetLibVersionResponseB\x1aZ\x18govirt/app/proto/libvirtb\x06proto3"

var (
	file_libvirt_libvirt_proto_rawDescOnce sync.Once
	file_libvirt_libvirt_proto_rawDescData []byte
)

func file_libvirt_libvirt_proto_rawDescGZIP() []byte {
	file_libvirt_libvirt_proto_rawDescOnce.Do(func() {
		file_libvirt_libvirt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libvirt_libvirt_proto_rawDesc), len(file_libvirt_libvirt_proto_rawDesc)))
	})
	return file_libvirt_libvirt_proto_rawDescData
}

var file_libvirt_libvirt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_libvirt_libvirt_proto_goTypes = []any{
	(*GetLibVersionRequest)(nil),  // 0: libvirt.GetLibVersionRequest
	(*GetLibVersionResponse)(nil), // 1: libvirt.GetLibVersionResponse
}
var file_libvirt_libvirt_proto_depIdxs = []int32{
	0, // 0: libvirt.LibvirtService.GetLibVersion:input_type -> libvirt.GetLibVersionRequest
	1, // 1: libvirt.LibvirtService.GetLibVersion:output_type -> libvirt.GetLibVersionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_libvirt_libvirt_proto_init() }
func file_libvirt_libvirt_proto_init() {
	if File_libvirt_libvirt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libvirt_libvirt_proto_rawDesc), len(file_libvirt_libvirt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libvirt_libvirt_proto_goTypes,
		DependencyIndexes: file_libvirt_libvirt_proto_depIdxs,
		MessageInfos:      file_libvirt_libvirt_proto_msgTypes,
	}.Build()
	File_libvirt_libvirt_proto = out.File
	file_libvirt_libvirt_proto_goTypes = nil
	file_libvirt_libvirt_proto_depIdxs = nil
}
