// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: libvirt/libvirt.proto

package libvirtPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLibVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLibVersionRequest) Reset() {
	*x = GetLibVersionRequest{}
	mi := &file_libvirt_libvirt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLibVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibVersionRequest) ProtoMessage() {}

func (x *GetLibVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libvirt_libvirt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibVersionRequest.ProtoReflect.Descriptor instead.
func (*GetLibVersionRequest) Descriptor() ([]byte, []int) {
	return file_libvirt_libvirt_proto_rawDescGZIP(), []int{0}
}

type GetLibVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLibVersionResponse) Reset() {
	*x = GetLibVersionResponse{}
	mi := &file_libvirt_libvirt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLibVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibVersionResponse) ProtoMessage() {}

func (x *GetLibVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libvirt_libvirt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibVersionResponse.ProtoReflect.Descriptor instead.
func (*GetLibVersionResponse) Descriptor() ([]byte, []int) {
	return file_libvirt_libvirt_proto_rawDescGZIP(), []int{1}
}

func (x *GetLibVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetLibvirtInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLibvirtInfoRequest) Reset() {
	*x = GetLibvirtInfoRequest{}
	mi := &file_libvirt_libvirt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLibvirtInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibvirtInfoRequest) ProtoMessage() {}

func (x *GetLibvirtInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libvirt_libvirt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibvirtInfoRequest.ProtoReflect.Descriptor instead.
func (*GetLibvirtInfoRequest) Descriptor() ([]byte, []int) {
	return file_libvirt_libvirt_proto_rawDescGZIP(), []int{2}
}

func (x *GetLibvirtInfoRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetLibvirtInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Capabilities  string                 `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Hypervisor    string                 `protobuf:"bytes,5,opt,name=hypervisor,proto3" json:"hypervisor,omitempty"`
	CpuModel      string                 `protobuf:"bytes,6,opt,name=cpuModel,proto3" json:"cpuModel,omitempty"`
	CpuCount      string                 `protobuf:"bytes,7,opt,name=cpuCount,proto3" json:"cpuCount,omitempty"`
	MemorySize    string                 `protobuf:"bytes,8,opt,name=memorySize,proto3" json:"memorySize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLibvirtInfoResponse) Reset() {
	*x = GetLibvirtInfoResponse{}
	mi := &file_libvirt_libvirt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLibvirtInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibvirtInfoResponse) ProtoMessage() {}

func (x *GetLibvirtInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libvirt_libvirt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibvirtInfoResponse.ProtoReflect.Descriptor instead.
func (*GetLibvirtInfoResponse) Descriptor() ([]byte, []int) {
	return file_libvirt_libvirt_proto_rawDescGZIP(), []int{3}
}

func (x *GetLibvirtInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetLibvirtInfoResponse) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *GetLibvirtInfoResponse) GetCapabilities() string {
	if x != nil {
		return x.Capabilities
	}
	return ""
}

func (x *GetLibvirtInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetLibvirtInfoResponse) GetHypervisor() string {
	if x != nil {
		return x.Hypervisor
	}
	return ""
}

func (x *GetLibvirtInfoResponse) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *GetLibvirtInfoResponse) GetCpuCount() string {
	if x != nil {
		return x.CpuCount
	}
	return ""
}

func (x *GetLibvirtInfoResponse) GetMemorySize() string {
	if x != nil {
		return x.MemorySize
	}
	return ""
}

var File_libvirt_libvirt_proto protoreflect.FileDescriptor

const file_libvirt_libvirt_proto_rawDesc = "" +
	"\n" +
	"\x15libvirt/libvirt.proto\x12\alibvirt\"\x16\n" +
	"\x14GetLibVersionRequest\"1\n" +
	"\x15GetLibVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"+\n" +
	"\x15GetLibvirtInfoRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xfc\x01\n" +
	"\x16GetLibvirtInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\"\n" +
	"\fcapabilities\x18\x03 \x01(\tR\fcapabilities\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x1e\n" +
	"\n" +
	"hypervisor\x18\x05 \x01(\tR\n" +
	"hypervisor\x12\x1a\n" +
	"\bcpuModel\x18\x06 \x01(\tR\bcpuModel\x12\x1a\n" +
	"\bcpuCount\x18\a \x01(\tR\bcpuCount\x12\x1e\n" +
	"\n" +
	"memorySize\x18\b \x01(\tR\n" +
	"memorySize2\xb3\x01\n" +
	"\x0eLibvirtService\x12N\n" +
	"\rGetLibVersion\x12\x1d.libvirt.GetLibVersionRequest\x1a\x1e.libvirt.GetLibVersionResponse\x12Q\n" +
	"\x0eGetLibvirtInfo\x12\x1e.libvirt.GetLibvirtInfoRequest\x1a\x1f.libvirt.GetLibvirtInfoResponseB\x1cZ\x1agovirt/app/proto/libvirtPbb\x06proto3"

var (
	file_libvirt_libvirt_proto_rawDescOnce sync.Once
	file_libvirt_libvirt_proto_rawDescData []byte
)

func file_libvirt_libvirt_proto_rawDescGZIP() []byte {
	file_libvirt_libvirt_proto_rawDescOnce.Do(func() {
		file_libvirt_libvirt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libvirt_libvirt_proto_rawDesc), len(file_libvirt_libvirt_proto_rawDesc)))
	})
	return file_libvirt_libvirt_proto_rawDescData
}

var file_libvirt_libvirt_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_libvirt_libvirt_proto_goTypes = []any{
	(*GetLibVersionRequest)(nil),   // 0: libvirt.GetLibVersionRequest
	(*GetLibVersionResponse)(nil),  // 1: libvirt.GetLibVersionResponse
	(*GetLibvirtInfoRequest)(nil),  // 2: libvirt.GetLibvirtInfoRequest
	(*GetLibvirtInfoResponse)(nil), // 3: libvirt.GetLibvirtInfoResponse
}
var file_libvirt_libvirt_proto_depIdxs = []int32{
	0, // 0: libvirt.LibvirtService.GetLibVersion:input_type -> libvirt.GetLibVersionRequest
	2, // 1: libvirt.LibvirtService.GetLibvirtInfo:input_type -> libvirt.GetLibvirtInfoRequest
	1, // 2: libvirt.LibvirtService.GetLibVersion:output_type -> libvirt.GetLibVersionResponse
	3, // 3: libvirt.LibvirtService.GetLibvirtInfo:output_type -> libvirt.GetLibvirtInfoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_libvirt_libvirt_proto_init() }
func file_libvirt_libvirt_proto_init() {
	if File_libvirt_libvirt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libvirt_libvirt_proto_rawDesc), len(file_libvirt_libvirt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libvirt_libvirt_proto_goTypes,
		DependencyIndexes: file_libvirt_libvirt_proto_depIdxs,
		MessageInfos:      file_libvirt_libvirt_proto_msgTypes,
	}.Build()
	File_libvirt_libvirt_proto = out.File
	file_libvirt_libvirt_proto_goTypes = nil
	file_libvirt_libvirt_proto_depIdxs = nil
}
